Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in development environment.
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in development environment.
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in development environment.
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in development environment.
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in development environment.
Migrations for 'api':
  api/migrations/0001_initial.py
    - Create model Department
    - Create model Student
    - Create model CourseUnit
    - Create model Attendance
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
REST API running in production environment.
Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 22, in <module>
    main()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/rest_framework/authtoken/models.py", line 9, in <module>
    class Token(models.Model):
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rd/Desktop/UA/UA_10_Semestre/ws_deployment/production/rest_api/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
